version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: test
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: test
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracledatabase
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: root

volumes:
  postgres_data:
  mysql_data:
  sqlserver_data:
  oracle_data: