server:
  port: 8093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

